[phases.setup]
nixPkgs = ['...', 'bun@1.2.8']
nixpkgsArchive = "master"  # Use the latest nixpkgs to get the newest Bun version

[variables]
NODE_ENV = "production"

[phases.install]
cmds = ["bun install"]


