nostr:
    privateKey: '${DVM_PRIVATE_KEY}'
    relayUrls:
        - 'wss://relay.wavefunc.live'
        # - 'ws://192.168.0.163:3002'
encryption:
    mode: 'optional'
mcp:
    name: 'Wavefunc DVMCP Bridge'
    about: 'Music, Radio and files related tools'
    serverId: 'wavefunc-dvmcp-bridge'
    clientVersion: '0.0.1'
    picture: 'https://wavefunc.live/logo.png'
    website: 'https://github.com/zeSchlausKwab/wavefunc'
    servers:
        - command: 'bun'
          args:
              - 'run'
              - 'src/music-recognition.ts'
          env:
              AUDD_API_TOKEN: '${AUDD_API_TOKEN}'
              DISCOGS_PA_TOKEN: '${DISCOGS_PA_TOKEN}'
          tools:
              - name: 'music-recognition'
                # price: '4'
                # unit: 'sats'
              - name: 'radio-search'
                price: '3'
                unit: 'sats'
        - command: 'bun'
          args:
              - 'run'
              - 'src/music-metadata.ts'
          env:
              DISCOGS_PA_TOKEN: '${DISCOGS_PA_TOKEN}'
          tools:
              - name: 'discogs-search'
              - name: 'discogs-release'
              - name: 'musicbrainz-search-recording'
              - name: 'musicbrainz-search-release'
              - name: 'musicbrainz-get-recording'
              - name: 'musicbrainz-get-release'
              - name: 'musicbrainz-search-artist'
              - name: 'musicbrainz-get-artist'
              - name: 'musicbrainz-search-label'
              - name: 'musicbrainz-get-label'
lightning:
    address: '${DVM_LIGHTNING_ADDRESS}'
    zapRelays:
        - 'wss://relay.minibits.cash'
        - 'wss://relay.wavefunc.live'
        # - 'ws://192.168.0.163:3002'
# whitelist:
# List of allowed public keys (leave empty for no restrictions)
# allowedPubkeys: []
