[package]
name = "tauri-plugin-wavefunc-player"
version = "0.1.0"
authors = ["WaveFunc"]
description = "Native Android background radio playback for WaveFunc"
edition = "2021"
rust-version = "1.77.2"
links = "tauri-plugin-wavefunc-player"

[dependencies]
serde = { version = "1", features = ["derive"] }
tauri = { version = "2" }
thiserror = "2"

[build-dependencies]
tauri-plugin = { version = "2", features = ["build"] }
